category: 'superhumannerf'
task: 'zju_mocap'
subject: '386'
experiment: 'baseline'
logdir: '../experiments/superhumannerf/zju_mocap/386/baseline'
##############################################3
## Network Specs

# modules
network_module: 'core.nets.human_nerf.network'
trainer_module: 'core.train.trainers.human_nerf.trainer'
lr_updater_module: 'core.train.trainers.human_nerf.lr_updaters.exp_decay'
optimizer_module: 'core.train.optimizers.human_nerf.optimizer'

mweight_volume:
  module: 'core.nets.human_nerf.mweight_vol_decoders.deconv_vol_decoder'
  embedding_size: 256
  volume_size: 32

non_rigid_motion_mlp:
  mlp_width: 128
  mlp_depth: 5
  kick_in_iter: 1000

pose_decoder:
  module: 'core.nets.human_nerf.pose_decoders.mlp_delta_body_pose'
  embedding_size: 69
  mlp_width: 128
  mlp_depth: 6
  kick_in_iter: 0

motionCLIP:
  encoded_feats: 'motionCLIP_token[s]_nbrs[1].pkl' # token: z/s(self); neighborhoods: #neighbors 
  training_frames_poseDistinct: False
  training_frames_lossDistinct: False 

##############################################
## Data Configuration

train:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_386_train'
  batch_size: 1
  shuffle: True
  drop_last: False
  lr: 0.0005  
  lr_mweight_vol_decoder: 0.00005 
  lr_pose_decoder: 0.00005        
  lr_non_rigid_mlp: 0.00005       
  lrate_decay: 100
  optimizer: 'adam'
  ray_shoot_mode: 'patch'
  maxiter: 10000       
  log_interval: 10          
  lossweights:
    lpips: 1.0
    rgb_loss: 0.5
    opacity: 0.1             
    mask_loss: 0.0
    tvloss_rgb: 0.0        
    tvloss_sigma: 0.0           
  opacity_kick_in_iter: 5000         

progress:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_386_test'
  batch_size: 1
  shuffle: False
  drop_last: False
  progress_interval: 1000     

movement:
  dataset_module: 'core.data.human_nerf.train'
  dataset: 'zju_386_test'
  batch_size: 1
  shuffle: False
  drop_last: False

freeview:
  dataset_module: 'core.data.human_nerf.freeview'
  dataset: 'zju_386_test'
  batch_size: 1
  shuffle: False
  drop_last: False
  frame_idx: 0

tpose:
  dataset_module: 'core.data.human_nerf.tpose'
  dataset: 'zju_386_test'
  batch_size: 1
  shuffle: False
  drop_last: False

bgcolor: [0., 0., 0.]

##############################################
## EXPERIMENTS CONFIGURATIONS

resize_img_scale: 0.5

train_keyfilter: ['rays', 'motion_bases', 'motion_weights_priors', 'cnl_bbox', 'dst_posevec_69', 'motionCLIP']
test_keyfilter: ['rays', 'target_rgbs', 'motion_bases', 'motion_weights_priors','cnl_bbox', 'dst_posevec_69', 'motionCLIP']

sex: 'neutral'
total_bones: 24
bbox_offset: 0.3  

resume: True
load_net: latest
save_all: True
eval_iter: 10000

patch:
  sample_subject_ratio: 1.0
  N_patches: 8       
  size: 64        

network:
  ignore_pose_correction: True
  ignore_non_rigid_motions: True
  apply_hash_coding: True

netchunk_per_gpu: 1048576

N_samples: 128      

chunk: 32768
perturb: 1
num_workers: 1
show_alpha: False  
show_truth: False